--
-- PostgreSQL database dump
--

\restrict Q8qqDUPF9dZi7MOV9edtqZuZl1Sk4cjchcIrW66UmH786xPtmCPJVgKiPs1N3Ga

-- Dumped from database version 15.16 (Debian 15.16-0+deb12u1)
-- Dumped by pg_dump version 15.16 (Debian 15.16-0+deb12u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: analytics_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.analytics_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    entity_id bigint,
    entity_name character varying(255),
    event_data text,
    event_type character varying(255) NOT NULL
);


--
-- Name: analytics_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.analytics_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analytics_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedback (
    id bigint NOT NULL,
    admin_response text,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    message text NOT NULL,
    name character varying(255) NOT NULL,
    phone character varying(255),
    responded_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    subject character varying(255),
    CONSTRAINT feedback_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'READ'::character varying, 'RESPONDED'::character varying, 'ARCHIVED'::character varying])::text[])))
);


--
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logs (
    id integer NOT NULL,
    user_id integer,
    action character varying(200),
    details text,
    "timestamp" timestamp without time zone DEFAULT now()
);


--
-- Name: logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.logs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.logs_id_seq OWNED BY public.logs.id;


--
-- Name: news_subscribers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news_subscribers (
    id bigint NOT NULL,
    active boolean NOT NULL,
    email character varying(255) NOT NULL,
    subscribed_at timestamp(6) without time zone,
    unsubscribe_token character varying(255) NOT NULL
);


--
-- Name: news_subscribers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news_subscribers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_subscribers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    admin_notes text,
    created_at timestamp(6) without time zone,
    currency character varying(255),
    customer_name character varying(255),
    deleted boolean,
    email character varying(255),
    estimated_delivery timestamp(6) without time zone,
    items_json text,
    order_id character varying(255) NOT NULL,
    paid_at timestamp(6) without time zone,
    payment_id character varying(100),
    payment_method character varying(255),
    phone character varying(255),
    shipping_address text,
    shipping_method character varying(255),
    status character varying(255) NOT NULL,
    total double precision,
    tracking_number character varying(255),
    updated_at timestamp(6) without time zone,
    user_id character varying(255),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PROCESSING'::character varying, 'CONFIRMED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poi_suggestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.poi_suggestions (
    id bigint NOT NULL,
    admin_notes text,
    created_at timestamp(6) without time zone,
    description text,
    name character varying(255) NOT NULL,
    place character varying(500) NOT NULL,
    reviewed_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    why_add text NOT NULL,
    imported_poi_id bigint,
    latitude double precision,
    longitude double precision,
    CONSTRAINT poi_suggestions_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: poi_suggestions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.poi_suggestions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.poi_suggestions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: points_of_interest; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.points_of_interest (
    id bigint NOT NULL,
    address character varying(255),
    architect character varying(255),
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    description text,
    email character varying(255),
    founded_year integer,
    image_data bytea,
    image_filename character varying(255),
    image_url character varying(255),
    latitude double precision,
    longitude double precision,
    material character varying(255),
    name character varying(255) NOT NULL,
    phone character varying(255),
    publish_at timestamp(6) without time zone,
    rating double precision,
    reviews_count integer,
    status character varying(255) NOT NULL,
    style character varying(255),
    tags character varying(255),
    unpublish_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    views_count bigint,
    website character varying(255),
    working_hours text,
    newsletter_notified boolean,
    CONSTRAINT points_of_interest_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PENDING'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying])::text[])))
);


--
-- Name: points_of_interest_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.points_of_interest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.points_of_interest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    category character varying(255),
    colors character varying(255),
    created_at timestamp(6) without time zone,
    currency character varying(255),
    description text,
    details text,
    image_data bytea,
    image_filename character varying(255),
    image_url character varying(255),
    in_stock boolean,
    material character varying(255),
    name character varying(255) NOT NULL,
    price double precision NOT NULL,
    published boolean,
    quantity integer,
    rating double precision,
    reviews_count integer,
    sizes character varying(255),
    updated_at timestamp(6) without time zone,
    weight character varying(255)
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    approved boolean,
    created_at timestamp(6) without time zone,
    helpful_count integer,
    poi_id bigint,
    rating integer,
    text text,
    user_id character varying(255),
    user_name character varying(255),
    visit_date character varying(255)
);


--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reward_redemption_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reward_redemption_events (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    route_id bigint NOT NULL,
    used_at timestamp(6) without time zone NOT NULL
);


--
-- Name: reward_redemption_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reward_redemption_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reward_redemption_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    permissions character varying(2000) DEFAULT '{}'::jsonb
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: route_completion_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.route_completion_events (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone NOT NULL,
    email character varying(254) NOT NULL,
    is_paid boolean NOT NULL,
    route_id bigint NOT NULL
);


--
-- Name: route_completion_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.route_completion_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_completion_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: routes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.routes (
    id bigint NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    difficulty character varying(255),
    distance double precision,
    duration integer,
    image_data bytea,
    image_filename character varying(255),
    image_url character varying(255),
    name character varying(255) NOT NULL,
    paid boolean,
    poi_ids character varying(255),
    price double precision,
    published boolean,
    rating double precision,
    priority integer DEFAULT 0 NOT NULL,
    status character varying(32) DEFAULT 'DRAFT'::character varying NOT NULL,
    outdated_reason text,
    updated_at timestamp(6) without time zone,
    waypoints text
);


--
-- Name: routes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: telegram_link_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.telegram_link_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(254),
    expires_at timestamp(6) without time zone NOT NULL,
    phone character varying(50),
    token_hash character varying(128) NOT NULL,
    used_at timestamp(6) without time zone
);


--
-- Name: telegram_link_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.telegram_link_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telegram_link_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_progress_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_progress_profiles (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    snapshot_json text,
    updated_at timestamp(6) without time zone
);


--
-- Name: user_progress_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_progress_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_progress_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_telegram_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_telegram_links (
    id bigint NOT NULL,
    email character varying(254),
    last_used_at timestamp(6) without time zone,
    linked_at timestamp(6) without time zone NOT NULL,
    phone character varying(50),
    telegram_chat_id bigint NOT NULL,
    telegram_username character varying(255),
    is_verified boolean NOT NULL
);


--
-- Name: user_telegram_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_telegram_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_telegram_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(120),
    last_login timestamp(6) without time zone,
    name character varying(100),
    password character varying(255) NOT NULL,
    role_id bigint,
    username character varying(100) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: visits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.visits (
    id integer NOT NULL,
    user_id integer,
    page character varying(200),
    "timestamp" timestamp without time zone DEFAULT now()
);


--
-- Name: visits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.visits_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: visits_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.visits_id_seq OWNED BY public.visits.id;


--
-- Name: logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logs ALTER COLUMN id SET DEFAULT nextval('public.logs_id_seq'::regclass);


--
-- Name: visits id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visits ALTER COLUMN id SET DEFAULT nextval('public.visits_id_seq'::regclass);


--
-- Name: analytics_events analytics_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.analytics_events
    ADD CONSTRAINT analytics_events_pkey PRIMARY KEY (id);


--
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- Name: logs logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT logs_pkey PRIMARY KEY (id);


--
-- Name: news_subscribers news_subscribers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_subscribers
    ADD CONSTRAINT news_subscribers_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: poi_suggestions poi_suggestions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.poi_suggestions
    ADD CONSTRAINT poi_suggestions_pkey PRIMARY KEY (id);


--
-- Name: points_of_interest points_of_interest_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.points_of_interest
    ADD CONSTRAINT points_of_interest_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: reward_redemption_events reward_redemption_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reward_redemption_events
    ADD CONSTRAINT reward_redemption_events_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: route_completion_events route_completion_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.route_completion_events
    ADD CONSTRAINT route_completion_events_pkey PRIMARY KEY (id);


--
-- Name: routes routes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT routes_pkey PRIMARY KEY (id);


--
-- Name: telegram_link_tokens telegram_link_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telegram_link_tokens
    ADD CONSTRAINT telegram_link_tokens_pkey PRIMARY KEY (id);


--
-- Name: user_progress_profiles uk2e0dlc3593718u2x2n2k6l93w; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_progress_profiles
    ADD CONSTRAINT uk2e0dlc3593718u2x2n2k6l93w UNIQUE (email);


--
-- Name: news_subscribers uk3q5o16jwixojkrun7po9gly8x; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_subscribers
    ADD CONSTRAINT uk3q5o16jwixojkrun7po9gly8x UNIQUE (unsubscribe_token);


--
-- Name: news_subscribers ukaoh6bnlhs8vkd7ilx2xbplomi; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news_subscribers
    ADD CONSTRAINT ukaoh6bnlhs8vkd7ilx2xbplomi UNIQUE (email);


--
-- Name: user_telegram_links ukc0iubkw2qopb33si98prt8oh3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_telegram_links
    ADD CONSTRAINT ukc0iubkw2qopb33si98prt8oh3 UNIQUE (telegram_chat_id);


--
-- Name: telegram_link_tokens ukgupyqdoaftj5b8f0q31di8jtn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telegram_link_tokens
    ADD CONSTRAINT ukgupyqdoaftj5b8f0q31di8jtn UNIQUE (token_hash);


--
-- Name: orders ukhmsk25beh6atojvle1xuymjj0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukhmsk25beh6atojvle1xuymjj0 UNIQUE (order_id);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: user_progress_profiles user_progress_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_progress_profiles
    ADD CONSTRAINT user_progress_profiles_pkey PRIMARY KEY (id);


--
-- Name: user_telegram_links user_telegram_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_telegram_links
    ADD CONSTRAINT user_telegram_links_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: visits visits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visits
    ADD CONSTRAINT visits_pkey PRIMARY KEY (id);


--
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: logs logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logs
    ADD CONSTRAINT logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: visits visits_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.visits
    ADD CONSTRAINT visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict Q8qqDUPF9dZi7MOV9edtqZuZl1Sk4cjchcIrW66UmH786xPtmCPJVgKiPs1N3Ga

